/** 系统权限码 */
export const PermissionCode = {
  NOTIFICATION_SEND: 'notification:send',
  NOTIFICATION_SENT_READ: 'notification:sent:read',
  NOTIFICATION_INBOX_READ: 'notification:inbox:read',
  NOTIFICATION_INBOX_UPDATE: 'notification:inbox:update',
  FILE_UPLOAD: 'file:upload',
  FILE_DOWNLOAD: 'file:download',
  FILE_READ: 'file:read',
  FILE_DELETE: 'file:delete',
  AUTH_PASSWORD_CHANGE: 'auth:password:change',
  AUTH_PERMISSIONS_READ: 'auth:permissions:read',
  USER_LIST_READ: 'user:list:read',
  USER_CREATE: 'user:create',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_PASSWORD_RESET: 'user:password:reset',
  USER_PROFILE_READ: 'user:profile:read',
  USER_PROFILE_UPDATE: 'user:profile:update',
  DEPT_LIST_READ: 'dept:list:read',
  DEPT_CREATE: 'dept:create',
  DEPT_UPDATE: 'dept:update',
  DEPT_DELETE: 'dept:delete',
  POSITION_LIST_READ: 'position:list:read',
  POSITION_CREATE: 'position:create',
  POSITION_UPDATE: 'position:update',
  POSITION_DELETE: 'position:delete',
  ROLE_LIST_READ: 'role:list:read',
  ROLE_CREATE: 'role:create',
  ROLE_UPDATE: 'role:update',
  ROLE_DELETE: 'role:delete',
  ROLE_PERMISSION_ASSIGN: 'role:permission:assign',
  ROLE_USER_ASSIGN: 'role:user:assign',
};

/** 权限码目录（与后台一致） */
export const PERMISSION_CATALOG = [
  { code: PermissionCode.NOTIFICATION_SEND, label: '发送站内信' },
  { code: PermissionCode.NOTIFICATION_SENT_READ, label: '查看已发送站内信' },
  { code: PermissionCode.NOTIFICATION_INBOX_READ, label: '查看本人收件箱' },
  { code: PermissionCode.NOTIFICATION_INBOX_UPDATE, label: '标记站内信已读' },
  { code: PermissionCode.FILE_UPLOAD, label: '上传文件' },
  { code: PermissionCode.FILE_DOWNLOAD, label: '下载文件' },
  { code: PermissionCode.FILE_READ, label: '查看文件信息' },
  { code: PermissionCode.FILE_DELETE, label: '删除文件' },
  { code: PermissionCode.AUTH_PASSWORD_CHANGE, label: '修改本人密码' },
  { code: PermissionCode.AUTH_PERMISSIONS_READ, label: '查看本人权限清单' },
  { code: PermissionCode.USER_LIST_READ, label: '查看用户列表' },
  { code: PermissionCode.USER_CREATE, label: '新增用户' },
  { code: PermissionCode.USER_UPDATE, label: '更新用户资料/状态/头像' },
  { code: PermissionCode.USER_DELETE, label: '删除用户' },
  { code: PermissionCode.USER_PASSWORD_RESET, label: '重置用户密码' },
  { code: PermissionCode.USER_PROFILE_READ, label: '查看本人资料' },
  { code: PermissionCode.USER_PROFILE_UPDATE, label: '更新本人资料' },
  { code: PermissionCode.DEPT_LIST_READ, label: '查看部门' },
  { code: PermissionCode.DEPT_CREATE, label: '创建部门' },
  { code: PermissionCode.DEPT_UPDATE, label: '更新部门' },
  { code: PermissionCode.DEPT_DELETE, label: '删除部门' },
  { code: PermissionCode.POSITION_LIST_READ, label: '查看职位' },
  { code: PermissionCode.POSITION_CREATE, label: '创建职位' },
  { code: PermissionCode.POSITION_UPDATE, label: '更新职位' },
  { code: PermissionCode.POSITION_DELETE, label: '删除职位' },
  { code: PermissionCode.ROLE_LIST_READ, label: '查看角色列表' },
  { code: PermissionCode.ROLE_CREATE, label: '创建角色' },
  { code: PermissionCode.ROLE_UPDATE, label: '更新角色' },
  { code: PermissionCode.ROLE_DELETE, label: '删除角色' },
  { code: PermissionCode.ROLE_PERMISSION_ASSIGN, label: '分配角色权限' },
  { code: PermissionCode.ROLE_USER_ASSIGN, label: '分配用户角色' },
];
